name: Paper Submission
description: Propose a new paper entry.
title: "[PAPER] "
labels:
  - paper-submission
  - needs-triage
body:
  - type: input
    id: paper_title
    attributes:
      label: Paper title
    validations:
      required: true
  - type: input
    id: year
    attributes:
      label: Year
      placeholder: "2025"
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Link (PDF / DOI / publisher)
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: general / methodology / application / ethics-policy / review
    validations:
      required: true
  - type: textarea
    id: file_content
    attributes:
      label: _papers/<slug>.md content
      render: markdown
    validations:
      required: true
